name: Deploy Portfolio Static
on:
  push:
    tags:
      - v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh/ && \
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/github_deploy && \
          chmod 600 ~/.ssh/github_deploy && \
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: sync static files
        run: |
          rsync -avz --delete \
          -e "ssh -p ${{ secrets.VPS_PORT }} -i ~/.ssh/github_deploy" \
          --exclude ".git" \
          --exclude ".github" \
          --exclude ".nojekyll" \
          --exclude ".gitignore" \
          ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_CATALOG }}/

